DROP DATABASE IF EXISTS epytodo;
CREATE DATABASE epytodo;
USE epytodo;
CREATE TABLE IF NOT EXISTS user (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, password VARCHAR(100), firstname VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS todo (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(100) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, due_time TIMESTAMP, description TEXT, status ENUM('not started', 'todo', 'in progress', 'done') DEFAULT 'not started', user_id INT, FOREIGN KEY(`user_id`)REFERENCES `user` (`id`));
