name: chocolatine

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-COT-2-1-chocolatine-brouhane.boni-gomina.git"
  EXECUTABLES: "tester.sh,sandpile,hello"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - id: check_coding_style
        run: check.sh $(pwd) $(pwd)
           
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - id: check_program_compilation
        run: |
          make && make clean
          IFS=',' read -ra executables <<< "${EXECUTABLES}"
          for executable in "${executables[@]}"; do
            if [[ ! -x "${executable}" ]]; then
              echo "Error: Bro, ${executable} n'existe pas inh, check bien et rééssaye"
              exit 84
            fi
          done
        timeout-minutes: 2

  run_tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - id: run_tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: [run_tests]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
