on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://github.com/Dinezimo/bootstrap_chocolatine.git'
            GIT_USERNAME: Dinezimo
            GIT_PASSWORD: "Dinichou1234"